SALSA_KEYS = {
    "donor id",
    "donor external id",
    "first name",
    "middle name",
    "last name",
    "email",
    "address line 1",
    "address line 2",
    "city",
    "state",
    "state code",
    "zip",
    "country",
    "country code",
    "activity summary id",
    "activity form name",
    "activity form id",
    "activity total amount",
    "activity type",
    "activity created date",
    "fund name",
    "appeal name",
    "campaign name",
    "designation",
    "dedication type",
    "dedication",
    "notify",
    "transaction id",
    "transaction type",
    "transaction reason",
    "transaction reason name",
    "transaction timestamp",
    "payment gateway",
    "transaction pnref",
    "transaction amount",
    "transaction fees paid",
    "transaction deductible amount",
    "account type",
    "account provider",
    "account number",
    "account exp",
    "was offline",
    "was imported",
    "was API imported",
    "Choose A Project:",
    "Memo",
    "Salsa Track"
}
CARDPOINTE_KEYS = {
        'Transaction #',
        'Location',
        'Date',
        'Method',
        'Name',
        'Brand',
        'Last 4',
        'Amount',
        'Auth Code',
        'Status',
        'Gateway Batch #',
        'FORM_NAME (Custom Field #0)'
}
